version: '3.1'

services:
  api:
    container_name: todoapp
    build: ./api
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: todoapp-db
    image: mongo
    restart: always
    ports:
      - 27777:27017
    volumes:
      - todoapp-dbdata:/data/db

volumes:
  todoapp-dbdata:
