version: '3.1'

services:
  # api:
  #   container_name: todoapp
  #   build: ./api
  #   ports:
  #     - 9090:8080
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: 8080
  #     AUTH_SECRET_KEY: /run/secrets/auth_key
  #     DB_CONNECTION_URI: mongodb://mongo:27017
  #     DB_NAME: todoapp
  #     DB_TASK_COLLECTION_NAME: tasks
  #     DB_USER_COLLECTION_NAME: users
  mongo:
    container_name: todoapp-db
    image: mongo
    restart: always
    ports:
      - 27777:27017
    volumes:
      - todoapp-dbdata:/data/db

volumes:
  todoapp-dbdata:

secrets:
  auth_key:
    file: ./auth_key.txt
