version: '3.1'

services:
  mongo:
    container_name: todoapp-db
    image: mongo
    restart: always
    ports:
      - 27777:27017
    volumes:
      - todoapp-dbdata:/data/db

volumes:
  todoapp-dbdata:
